[package]
name = "super-haskell-backend"
version = "0.1.0"
edition = "2021"
authors = ["Ahmad Parr <ahmedparr93@gmail.com>"]
license = "BSL-1.1 OR AGPL-3.0-or-later OR MPL-2.0"

[lib]
name = "super_haskell_backend"
crate-type = ["cdylib", "staticlib"]

[dependencies]
blake3 = "1.5"
sha2 = "0.10"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "crypto_bench"
harness = false
