[package]
name = "hyperkitty-worm"
version = "0.1.0"
edition = "2021"
authors = ["SNAPKITTYWEST"]
description = "Binary WORM storage"
license = "MIT"

[dependencies]
hyperkitty-core = { workspace = true }
blake2 = "0.10"
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
serde = { workspace = true }
rand = "0.8"
sha2 = "0.10"
